import assert from 'node:assert/strict';
import {blendExpressions,clothingTintRegion} from '../assets/characters/runtime.js';
const face={};
blendExpressions(face,'happy',0,true);
assert.equal(face.happy,.7);
blendExpressions(face,'surprised',.016);
assert.ok(face.happy>0 && face.surprised>0);
assert.ok(Object.values(face).reduce((a,b)=>a+b,0)<=1);
for(let i=0;i<180;i++)blendExpressions(face,'neutral',1/60);
assert.ok(Object.values(face).every(v=>v<1e-5));
for(const name of Object.keys(face))face[name]=1;
blendExpressions(face,'wink',.016);
assert.ok(Object.values(face).reduce((a,b)=>a+b,0)<=1+1e-12);
console.log('Expression transitions preserve neutral and bounded combined morph weight');
assert.equal(clothingTintRegion('noah reference Hoodie green'),'top');
assert.equal(clothingTintRegion('jules reference Sweatshirt cream'),'top');
assert.equal(clothingTintRegion('claire reference Cardigan blue'),'top');
assert.equal(clothingTintRegion('noah reference Cargo beige'),'bottom');
assert.equal(clothingTintRegion('jules reference Denim blue'),'bottom');
assert.equal(clothingTintRegion('mara reference Outfit charcoal'),null);
assert.equal(clothingTintRegion('Wardrobe'),null);
